api/urls.py
from django.urls import path, re_path
from . import views
from lib.rest_framework_mvt_views import mvt_view_factory
from sequence.models import Sequence, Image, MapFeature
from guidebook.models import Scene
from rest_framework_simplejwt import views as jwt_views
urlpatterns = [
    # re_path(r'^(?P<version>(v1))/mapillary/token/verify', views.MapillaryTokenVerify.as_view(), name='api.mapillary.token_verify'),
    re_path(r'^(?P<version>(v1))/sequence/create', views.SequenceCreate.as_view(), name="api.sequence.create"),
    re_path(r'^(?P<version>(v1))/sequence/import/(?P<unique_id>[\w-]+)/$', views.SequenceImport.as_view(), name="api.sequence.import"),




    # re_path(r'^(?P<version>(v1|v2))/sequence/import', views.SequenceImport.as_view(), name="api.sequence.import"),
    re_path(r'^(?P<version>(v1))/sequence.mvt', mvt_view_factory(model_class=Sequence, geom_col='geometry_coordinates'), name="api.sequence.mvt"),
    re_path(r'^(?P<version>(v1))/image.mvt', mvt_view_factory(model_class=Image, geom_col='point'), name="api.sequence.image_mvt"),
    re_path(r'^(?P<version>(v1))/map-feature.mvt', mvt_view_factory(model_class=MapFeature, geom_col='geometry_point'),
            name="api.sequence.map_feature_mvt"),
    re_path(r'^(?P<version>(v1))/scene.mvt', mvt_view_factory(model_class=Scene, geom_col='point'), name="api.guidebook.scene_mvt"),

]

guidebook/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.home, name='guidebook.home'),
    path('create', views.guidebook_create, name='guidebook.create'),
    path('<str:unique_id>/edit/', views.guidebook_create, name='guidebook.guidebook_edit'),
    path('list/', views.guidebook_list, name='guidebook.guidebook_list'),
    path('my-guidebook-list/', views.my_guidebook_list, name='guidebook.my_guidebook_list'),
    path('<str:unique_id>/detail/', views.guidebook_detail, name='guidebook.guidebook_detail'),
    path('<str:unique_id>/check_like/', views.check_like, name='guidebook.check_like'),
    path('<str:unique_id>/check_publish/', views.check_publish, name='guidebook.check_publish'),
    path('<str:unique_id>/delete/', views.guidebook_delete, name='guidebook.guidebook_delete'),

    path('<str:unique_id>/scene/', views.add_scene, name='guidebook.add_scene'),
    path('<str:unique_id>/ajax/save_scene/', views.ajax_add_scene, name='guidebook.ajax_add_scene'),
    path('<str:unique_id>/ajax_get_detail/', views.ajax_get_detail, name='guidebook.ajax_get_detail'),
    path('<str:unique_id>/ajax/upload_file/', views.ajax_upload_file, name='guidebook.ajax_upload_file'),
    path('<str:unique_id>/ajax/guidebook_update/', views.ajax_guidebook_update, name='guidebook.ajax_guidebook_update'),
    path('<str:unique_id>/ajax/order_scene/', views.ajax_order_scene, name='guidebook.ajax_order_scene'),

    path('<str:unique_id>/scene/ajax/save_poi/<int:pk>/', views.ajax_save_poi, name='guidebook.ajax_save_poi'),
    path('<str:unique_id>/scene/ajax/delete_poi/<int:pk>/', views.ajax_delete_poi, name='guidebook.ajax_delete_poi'),

    path('<str:unique_id>/scene/ajax/delete_scene/<int:pk>/', views.ajax_delete_scene, name='guidebook.ajax_delete_scene'),

    path('<str:unique_id>/scene/ajax/add_scene_external_url/<int:pk>/', views.ajax_add_scene_external_url, name='guidebook.ajax_add_scene_external_url'),
    path('<str:unique_id>/scene/ajax/delete_scene_external_url/<int:pk>/', views.ajax_delete_scene_external_url, name='guidebook.ajax_delete_scene_external_url'),
    path('<str:unique_id>/scene/ajax/add_external_url/<int:pk>/', views.ajax_add_external_url, name='guidebook.ajax_add_external_url'),
    path('<str:unique_id>/scene/ajax/delete_external_url/<int:pk>/', views.ajax_delete_external_url, name='guidebook.ajax_delete_external_url'),

    path('<str:unique_id>/ajax/edit/get_scene/', views.ajax_get_edit_scene, name='guidebook.ajax_get_edit_scene'),
    path('<str:unique_id>/ajax/edit/set_starting_view/', views.ajax_set_start_view, name='guidebook.ajax_set_start_view'),
    path('<str:unique_id>/ajax/get_scene/', views.ajax_get_scene, name='guidebook.ajax_get_scene'),
    path('<str:unique_id>/ajax/get_scene_list/', views.ajax_get_scene_list, name='guidebook.ajax_get_scene_list'),

    path('ajax_get_detail_by_image_key/<str:image_key>', views.ajax_get_detail_by_image_key, name='guidebook.ajax_get_detail_by_image_key'),

    path('<str:unique_id>/scene/ajax_upload_scene_image/<str:scene_id>', views.ajax_upload_scene_image, name='guidebook.ajax_upload_scene_image'),
    path('<str:unique_id>/scene/ajax_upload_scene_video/<str:scene_id>', views.ajax_upload_scene_video, name='guidebook.ajax_upload_scene_video'),
    path('<str:unique_id>/scene/<str:scene_id>/ajax_upload_poi_image/<str:poi_id>', views.ajax_upload_poi_image, name='guidebook.ajax_upload_poi_image'),
    path('<str:unique_id>/scene/<str:scene_id>/ajax_upload_poi_video/<str:poi_id>', views.ajax_upload_poi_video,
         name='guidebook.ajax_upload_poi_video'),

    path('<str:unique_id>/scene/ajax_scene_media_delete/<str:scene_id>', views.ajax_scene_media_delete, name='guidebook.ajax_scene_media_delete'),
    path('<str:unique_id>/scene/<str:scene_id>/ajax_poi_media_delete/<str:poi_id>', views.ajax_poi_media_delete,
         name='guidebook.ajax_poi_media_delete'),

]

guidebook/models.py
## Django Packages
## Python Packages
import uuid
from datetime import datetime

from django.contrib.auth import (
    get_user_model, )
from django.contrib.gis.db import models
from django.urls import reverse

from lib.mvtManager import CustomMVTManager
from lib.functions import get_current_timestamp
from sys_setting.models import Tag
from sequence.models import Sequence

from django.conf import settings
from storages.backends.s3boto3 import S3Boto3Storage

UserModel = get_user_model()





def image_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    current_time = get_current_timestamp()
    return 'guidebook/{0}/cover_image/{1}.jpg'.format(instance.unique_id, current_time)


def scene_image_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    current_time = get_current_timestamp()
    path = 'guidebook/{}/scene/{}_{}.jpg'.format(instance.guidebook.unique_id, instance.unique_id, current_time)
    print(path)
    return path


def poi_image_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    current_time = get_current_timestamp()
    return 'guidebook/{}/scene/{}/poi/{}_{}.jpg'.format(instance.scene.guidebook.unique_id, instance.scene.unique_id, instance.pk, current_time)



# class Tag(models.Model):
#     alphanumeric = RegexValidator(r'^[0-9a-zA-Z-]*$', 'Only alphanumeric characters are allowed for Username.')
#     name = models.CharField(max_length=50, unique=True, null=True, validators=[alphanumeric])
#     description = models.TextField(default=None, blank=True, null=True)
#     is_actived = models.BooleanField(default=True)
#
#     def __str__(self):
#         return self.name


def getAllTags():
    items = Tag.objects.filter(is_actived=True)
    itemsTuple = ()
    for item in items:
        itemsTuple = itemsTuple + ((item.pk, item.name),)
    return itemsTuple


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Guidebook(models.Model):
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    cover_image = models.ImageField(upload_to=image_directory_path, null=True)
    tag = models.ManyToManyField(Tag)
    is_published = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.now, blank=True)

    like_count = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('guidebook.guidebook_detail', kwargs={'unique_id': str(self.unique_id)})

    def getScenes(self):
        scenes = Scene.objects.filter(guidebook=self).order_by('sort')
        return scenes

    def getScenePositions(self):
        scenes = Scene.objects.filter(guidebook=self)
        positions = []
        if scenes and scenes.count() > 0:
            for scene in scenes:
                position = [scene.lat, scene.lng]
                positions.append(position)
        return positions

    def getFirstScene(self):
        scenes = Scene.objects.filter(guidebook=self).order_by('sort')
        if scenes and scenes.count() > 0:
            firstScene = scenes[0]
            return firstScene
        else:
            return ''

    def getSceneCount(self):
        scenes = Scene.objects.filter(guidebook=self)
        return scenes.count()

    def get_like_count(self):
        liked_guidebook = GuidebookLike.objects.filter(guidebook=self)
        if not liked_guidebook:
            return 0
        else:
            return liked_guidebook.count()

    def get_short_description(self):
        description = self.description
        if len(description) > 100:
            return description[0:100] + '...'
        else:
            return description

    def get_tag_str(self):
        tags = []
        if self.tag is None:
            return ''
        for tag in self.tag.all():
            if tag and tag.is_actived:
                tags.append(tag.name)

        if len(tags) > 0:
            return ', '.join(tags)
        else:
            return ''

    def get_tags(self):
        tags = []
        if self.tag is None:
            return []
        for tag in self.tag.all():
            if tag and tag.is_actived:
                tags.append(tag.name)
        return tags

    def get_cover_image(self):
        scenes = Scene.objects.filter(guidebook=self)
        if scenes.count() > 0:
            return scenes[0].image_key
        else:
            return None

    def get_cover_imageUserOnMapillary(self):
        scenes = Scene.objects.filter(guidebook=self)
        if scenes.count() > 0:
            return scenes[0].username
        else:
            return ''


class GuidebookLike(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    guidebook = models.ForeignKey(Guidebook, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.now, blank=True)


class POICategory(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'POI Categories'


class CustomSceneMVTManager(CustomMVTManager):
    def get_additional_where(self, additional_filters={}, request=None):
        from tour.models import Tour
        additional_where = ""
        page_name = ''
        if 'page_name' in additional_filters.keys() and additional_filters['page_name'] != '':
            page_name = additional_filters['page_name']
        else:
            return ''

        if page_name == 'guidebook_detail' and request.session['guidebooks_query'] is not None:
            additional_where = ' AND guidebook_id in ( SELECT t.id as id FROM (' + request.session['guidebooks_query'] + ') as t )'

        return additional_where


class SceneExternalURL(models.Model):
    external_url = models.TextField(default='')

    class Meta:
        ordering = ['external_url']

    def __str__(self):
        return self.external_url

    def short_external_url(self):
        external_url = self.external_url
        if len(external_url) > 30:
            return external_url[0:30] + '...'
        else:
            return external_url


class Scene(models.Model):
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    guidebook = models.ForeignKey(Guidebook, on_delete=models.CASCADE)
    image_key = models.CharField(max_length=100)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True)
    lat = models.FloatField(default=0)
    lng = models.FloatField(default=0)
    point = models.PointField(null=True, blank=True)
    start_x = models.FloatField(default=0.5)
    start_y = models.FloatField(default=0.5)
    sort = models.IntegerField(default=1, null=True)
    image_url = models.CharField(max_length=100, null=True, blank=True)
    username = models.CharField(max_length=100, default='', null=True, blank=True, verbose_name="Mapillary Username", )

    video_url = models.TextField(default='', blank=True)
    image = models.ImageField(upload_to=scene_image_directory_path, max_length=255, null=True, blank=True, storage=S3Boto3Storage(bucket=settings.AWS_STORAGE_BUCKET_NAME))

    external_url = models.ManyToManyField(SceneExternalURL, blank=True)

    objects = models.Manager()
    vector_tiles = CustomSceneMVTManager(
        geo_col='point',
        select_columns=['image_key', 'unique_id'],
        is_show_id=False,
        source_layer='mtp-scenes'
    )

    def get_poi_count(self):
        points_of_interest = PointOfInterest.objects.filter(scene=self)
        return points_of_interest.count()

    def get_poi_categories(self):
        points_of_interest = PointOfInterest.objects.filter(scene=self)
        categories = []
        if points_of_interest.count() > 0:
            for poi in points_of_interest:
                if poi.category.name not in categories:
                    categories.append(poi.category.name)
        if len(categories) > 0:
            return ', '.join(categories)
        else:
            return ''

    def get_sequence(self):
        sequences = Sequence.objects.filter(coordinates_image__contains=[self.image_key])
        if sequences.count() == 0:
            return None
        else:
            return sequences[0]

    def get_external_urls(self):
        external_urls = self.external_url.all()
        return external_urls


class POIExternalURL(models.Model):
    external_url = models.TextField(default='')

    class Meta:
        ordering = ['external_url']

    def __str__(self):
        return self.external_url

    def short_external_url(self):
        external_url = self.external_url
        if len(external_url) > 30:
            return external_url[0:30] + '...'
        else:
            return external_url


class PointOfInterest(models.Model):
    scene = models.ForeignKey(Scene, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, default='')
    description = models.TextField(default='')
    position_x = models.FloatField(default=0)
    position_y = models.FloatField(default=0)
    category = models.ForeignKey(POICategory, on_delete=models.CASCADE, default=1)
    video_url = models.TextField(default='')

templates/guidebook/create_main.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block app_guidebook %}active{% endblock %}
{% block app_style %}<link rel="stylesheet" href="{% static 'css/guidebook_style.css' %}">{% endblock %}
{% block content %}
<div class="main-body">
    <div class="page-header d-none">
        <div class="pt-3 mb-3">
            <h4>
                {{ pageName }}
            </h4>
        </div>

        <p>
            {{ pageDescription }}
        </p>
    </div>
    <div class="w-100 mt-5 d-flex justify-content-center">
        <div class="p-3" style="width: 400px">
             <form method="POST" class="post-form" id="guidebook_create_form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                 <input name="image_key" type="text" class="d-none" value="{{ image_key }}">
                <div class="form-group d-flex justify-content-between">
                    <button type="button" class="btn btn-info" onclick="window.history.back()">Back</button>
                    <button type="submit" class="save btn btn-primary save-btn">Continue</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/guidebook/modal_detail.html
{% load static %}
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="guidebookDetailModalTitle">Guidebooks</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% for guidebook in guidebooks %}
                <div class="card p-2 mt-2">
                    <div class="guidebook-title">
                        <h5>{{ guidebook.name }}</h5>
                    </div>
                    <div class="guidebook-description">
                        <p>
                            {{ guidebook.description }}
                        </p>
                    </div>
                    <div class="link text-right">
                        <a type="button" href="{% url 'guidebook.guidebook_detail' unique_id=guidebook.unique_id %}" id="show_guidebook" class="btn btn-sm btn-success text-light" >Go to Detail Page</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>

templates/guidebook/poi_box.html
<div class="card poi" id="poi_{{ poi.pk }}">
    <div class="card-header " id="poi_header_{{ poi.pk }}">
        <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left collapse-button" data-poi-id="{{ poi.pk }}" type="button" data-toggle="collapse" data-target="#poi_body_{{ poi.pk }}" aria-expanded="true" aria-controls="collapseOne">
                {{ poi.title }}
            </button>
        </h2>
    </div>
    <div id="poi_body_{{ poi.pk }}" class="collapse" aria-labelledby="poi_header_{{ poi.pk }}" data-parent="#poi_list">
        <div class="card-body">
            {% if poi.video_url is not None and poi.video_url != '' %}
                <iframe class="w-100 ml-auto mr-auto" height="200" src="{{ poi.video_url }}">
                </iframe>
            {% elif poi.image is not None and poi.image != '' %}
                <img class="w-100" height="200" src="{{ STATIC_URL }}{{ poi.image }}" />
            {% endif %}
            <div class="poi-description">
                <span>{{ poi.description }}</span>
            </div>
            <div class="poi-cetegory mt-2" style="color: blueviolet;">
                <p class="mb-1">
                    {{ poi.category }}
                </p>
            </div>
            <div class="d-flex justify-content-between">
                <span>External URLs: </span>
            </div>
            <ul class="d-flex flex-column pl-1" style="list-style-type: none" >
                {% for external_url in poi.get_external_urls %}
                    <li id="external_url_{{ external_url.pk }}">
                        <a href="{{ external_url.external_url }}" target="_blank">{{ external_url.short_external_url }}</a>
                    </li>
                {% endfor %}
            </ul>
            <div class="d-none">
                <div class=""><span>X: </span><span class="position-x">{{ poi.position_x }}</span></div>
                <div class=""><span>Y: </span><span class="position-y">{{ poi.position_y }}</span></div>
            </div>
        </div>
    </div>
</div>

templates/guidebook/poi_edit_box.html
<div class="card poi" id="poi_{{ poi.pk }}">
    <div class="card-header " id="poi_header_{{ poi.pk }}">
        <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left collapse-button" data-poi-id="{{ poi.pk }}" type="button" data-toggle="collapse" data-target="#poi_body_{{ poi.pk }}" aria-expanded="true" aria-controls="collapseOne">
{#                {{ poi.pk }}#}
                {{ poi.title }}
            </button>
        </h2>
    </div>

    <div id="poi_body_{{ poi.pk }}" class="collapse" aria-labelledby="poi_header_{{ poi.pk }}" data-parent="#poi_list">
        <div class="card-body">
            <form method="post">
                {{ poi_form.as_p }}

                <div class="external-url-list">
                    <div class="d-flex justify-content-between">
                        <span>External URLs: </span>
                        <button type="button" class="save btn btn-warning btn-sm save-btn add-external-url" onclick="addExternalURL('{{ poi.pk }}')" data-poi-id="{{ poi.pk }}" >Add External URL</button>
                    </div>
                    <div>
                        <textarea rows="1" class="form-control mt-1" placeholder="Please input external URL" id="input_external_url_{{ poi.pk }}"></textarea>
                    </div>
                    <ul class="d-flex flex-column" style="list-style-type: none" >
                        {% for external_url in poi.get_external_urls %}
                            <li id="external_url_{{ external_url.pk }}">
                                <a href="{{ external_url.external_url }}" target="_blank">{{ external_url.short_external_url }}</a>
                                <i class="far fa-times-circle" onclick="deleteExternalURL('{{ poi.pk }}', '{{ external_url.pk }}')" style="font-size: 15px; cursor: pointer"></i>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="d-flex align-items-center justify-content-between">
                    <div class="text-left">
                        <div class="d-none"><span>X: </span><span class="position-x">{{ poi.position_x }}</span></div>
                        <div class="d-none"><span>Y: </span><span class="position-y">{{ poi.position_y }}</span></div>
                    </div>

                    <div class="w-100">
                        <div class="media-box">
                            <div class="added-media">
                                {% if poi.video_url is not None and poi.video_url != '' %}
                                    <iframe class="w-100 ml-auto mr-auto" height="200" src="{{ poi.video_url }}">
                                    </iframe>
                                {% elif poi.is_exist_image %}
                                    <img class="w-100" height="200" src="{{ STATIC_URL }}{{ poi.image }}" />
                                {% endif %}
                            </div>
                            <div class="w-100 btn-group dropup media-actions text-right">
                                {% if poi.video_url is not None and poi.video_url != '' %}
                                    <div class="w-100 add-actions d-none">
                                        <div class="w-100 text-center mb-1">
                                            <h6>Link video or image to this POI.</h6>

                                            You can link video or upload image for your POI.
                                        </div>
                                        <a class="btn btn-warning btn-sm" href="javascript:showPOIVideoModal();">Add Video</a>
                                        <a class="btn btn-warning btn-sm ml-3" href="javascript:uploadPOIImage();">Add Photo</a>
                                    </div>

                                    <div class="w-100 delete-action">
                                        <a class="btn btn-danger btn-sm ml-3" href="javascript:deleteMedia();">Delete Media</a>
                                    </div>
                                {% elif poi.is_exist_image %}
                                    <div class="w-100 add-actions d-none">
                                        <div class="w-100 text-center mb-1">
                                            <h6>Link video or image to this POI.</h6>

                                            You can link video or upload image for your POI.
                                        </div>
                                        <a class="btn btn-warning btn-sm" href="javascript:showPOIVideoModal();">Add Video</a>
                                        <a class="btn btn-warning btn-sm ml-3" href="javascript:uploadPOIImage();">Add Photo</a>
                                    </div>

                                    <div class="w-100 delete-action">
                                        <a class="btn btn-danger btn-sm ml-3" href="javascript:deleteMedia();">Delete Media</a>
                                    </div>
                                {% else %}
                                    <div class="w-100 add-actions">
                                        <div class="w-100 text-center mb-1">
                                            <h6>Link video or image to this POI.</h6>

                                            You can link video or upload image for your POI.
                                        </div>
                                        <a class="btn btn-warning btn-sm" href="javascript:showPOIVideoModal();">Add Video</a>
                                        <a class="btn btn-warning btn-sm ml-3" href="javascript:uploadPOIImage();">Add Photo</a>
                                    </div>

                                    <div class="w-100 delete-action d-none">
                                        <a class="btn btn-danger btn-sm ml-3" href="javascript:deleteMedia();">Delete Media</a>
                                    </div>
                                {% endif %}



{#                                <button type="button" class="btn btn-sm btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                                    Add photo or video#}
{#                                </button>#}
{#                                <div class="dropdown-menu">#}
{#                                    <a class="dropdown-item" href="javascript:showPOIVideoModal();">Link Video</a>#}
{#                                    <a class="dropdown-item" href="javascript:uploadPOIImage();">Upload Image</a>#}
{#                                </div>#}
                            </div>
                        </div>

                        <hr class="mt-1 mb-1">

                        <div class="w-100 text-right mt-2">
                            <button type="button" class="save btn btn-danger btn-sm delete-btn delete-poi-button" data-poi-id="{{ poi.pk }}" >Delete</button>
                            <button type="button" class="save btn btn-primary btn-sm save-btn save-poi-button" data-poi-id="{{ poi.pk }}" >Save</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

templates/guidebook/scene_edit_box.html
<div class="list_item">
    <div class="scene-box p-1 mt-2 mb-2" id="scene_{{ scene.pk }}" data-scene-id="{{ scene.pk }}" data-image_key="{{ scene.image_key }}" style="cursor: pointer">
        <form method="POST" class="post-form has-validation-callback" id="add_scene_form_{{ scene.pk }}">
            {% csrf_token %}
            <input type="number" name="scene_id" class="d-none" value="{{ scene.pk }}" id="id_scene_id">
            <input type="text" name="image_key" class="form-control d-none" value="{{ scene.image_key }}" required="" id="id_image_key">
            <input type="text" name="title" class="form-control mb-1" disabled="disabled" value="{{ scene.title }}" placeholder="Scene Title" required="" id="id_title">
            <textarea name="description" cols="40" rows="3" disabled class="form-control mb-1" placeholder="Scene Description" style="resize: none;" id="id_description">{{ scene.description }}</textarea>
            <input type="text" name="lat" class="form-control d-none" value="{{ scene.lat }}" required="" id="id_lat">
            <input type="text" name="lng" class="form-control d-none" value="{{ scene.lng }}" required="" id="id_lng">
            <input type="text" name="start_x" class="form-control d-none" value="{{ scene.start_x }}" required="" id="id_start_x">
            <input type="text" name="start_y" class="form-control d-none" value="{{ scene.start_y }}" required="" id="id_start_y">
            <div class="text-right">
                <button type="button" class="btn btn-sm btn-info point_list" onclick="showPOIList('{{ scene.pk }}')" data-scene-id="{{ scene.pk }}">Edit POI's ({{ scene.get_poi_count }})</button>
                <button type="button" id="change_scene_button" class="save btn btn-sm btn-warning change-btn" onclick="enable_scene_form({{ scene.pk }})">Edit Scene</button>
                <button type="button" id="save_scene_button" class="save btn btn-sm btn-primary save-btn d-none" onclick="saveScene('{% url "guidebook.ajax_add_scene" unique_id=guidebook.unique_id %}', {{ scene.pk }})">Save</button>
                <button type="button" class="btn btn-sm btn-danger delete_scene_button" data-scene-id="{{ scene.pk }}">Delete</button>
            </div>
        </form>
    </div>
</div>

templates/guidebook/scene_external_box.html
<div class="d-flex justify-content-between">
    <span>External URLs: </span>
</div>
<ul class="d-flex flex-column pl-1" style="list-style-type: none" >
    {% for external_url in scene.get_external_urls %}
        <li id="external_url_{{ external_url.pk }}">
            <a href="{{ external_url.external_url }}" target="_blank">{{ external_url.short_external_url }}</a>
        </li>
    {% endfor %}
</ul>

templates/guidebook/scene_external_edit_box.html
<div class="scene-external-url-list">
    <div class="d-flex justify-content-between">
        <span>External URLs: </span>
        <button type="button" class="save btn btn-warning btn-sm save-btn add-external-url" onclick="addSceneExternalURL()" >Add External URL</button>
    </div>
    <div>
        <textarea rows="1" class="form-control mt-1" placeholder="Please input external URL" id="input_scene_external_url_{{ scene.pk }}"></textarea>
    </div>
    <ul class="d-flex flex-column" style="list-style-type: none" >
        {% for external_url in scene.get_external_urls %}
            <li id="scene_external_url_{{ external_url.pk }}">
                <a href="{{ external_url.external_url }}" target="_blank">{{ external_url.short_external_url }}</a>
                <i class="far fa-times-circle" onclick="deleteSceneExternalURL('{{ external_url.pk }}')" style="font-size: 15px; cursor: pointer"></i>
            </li>
        {% endfor %}
    </ul>
</div>