api/urls.py
from django.urls import path, re_path
from . import views
from lib.rest_framework_mvt_views import mvt_view_factory
from sequence.models import Sequence, Image, MapFeature
from guidebook.models import Scene
from rest_framework_simplejwt import views as jwt_views
urlpatterns = [
    # re_path(r'^(?P<version>(v1))/mapillary/token/verify', views.MapillaryTokenVerify.as_view(), name='api.mapillary.token_verify'),
    re_path(r'^(?P<version>(v1))/sequence/create', views.SequenceCreate.as_view(), name="api.sequence.create"),
    re_path(r'^(?P<version>(v1))/sequence/import/(?P<unique_id>[\w-]+)/$', views.SequenceImport.as_view(), name="api.sequence.import"),




    # re_path(r'^(?P<version>(v1|v2))/sequence/import', views.SequenceImport.as_view(), name="api.sequence.import"),
    re_path(r'^(?P<version>(v1))/sequence.mvt', mvt_view_factory(model_class=Sequence, geom_col='geometry_coordinates'), name="api.sequence.mvt"),
    re_path(r'^(?P<version>(v1))/image.mvt', mvt_view_factory(model_class=Image, geom_col='point'), name="api.sequence.image_mvt"),
    re_path(r'^(?P<version>(v1))/map-feature.mvt', mvt_view_factory(model_class=MapFeature, geom_col='geometry_point'),
            name="api.sequence.map_feature_mvt"),
    re_path(r'^(?P<version>(v1))/scene.mvt', mvt_view_factory(model_class=Scene, geom_col='point'), name="api.guidebook.scene_mvt"),

]

challenge/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [

    path('capture/', views.index, name='challenge.index'),

    path('capture/create', views.challenge_create, name='challenge.challenge_create'),
    path('capture/<str:unique_id>/edit/', views.challenge_edit, name='challenge.my_challenge_edit'),
    path('capture/my-list/', views.my_challenge_list, name='challenge.my_challenge_list'),
    path('capture/list/', views.challenge_list, name='challenge.challenge_list'),
    path('capture/<str:unique_id>/delete/', views.my_challenge_delete, name='challenge.my_challenge_delete'),
    path('capture/<str:unique_id>/', views.challenge_detail, name='challenge.challenge_detail'),
    path('capture/<str:unique_id>/leaderboard/', views.challenge_leaderboard, name='challenge.challenge_leaderboard'),
    path('capture/ajax/get_challenge_detail/<str:unique_id>/', views.ajax_challenge_detail, name='challenge.ajax_challenge_detail'),

    path('label/create', views.label_challenge_create, name='challenge.label_challenge_create'),
    path('label/<str:unique_id>/edit/', views.label_challenge_edit, name='challenge.my_label_challenge_edit'),
    path('label/my-list/', views.my_label_challenge_list, name='challenge.my_label_challenge_list'),
    path('label/list/', views.label_challenge_list, name='challenge.label_challenge_list'),
    path('label/<str:unique_id>/delete/', views.my_label_challenge_delete, name='challenge.my_label_challenge_delete'),
    path('label/<str:unique_id>/', views.label_challenge_detail, name='challenge.label_challenge_detail'),
    path('label/<str:unique_id>/leaderboard/', views.label_challenge_leaderboard, name='challenge.label_challenge_leaderboard'),
    path('label/ajax/get_challenge_detail/<str:unique_id>/', views.ajax_label_challenge_detail, name='challenge.ajax_label_challenge_detail'),
]

leaderboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='leaderboard.index'),
]

challenge/models.py
import uuid
from datetime import datetime

from django.contrib.auth import (
    get_user_model, )
from django.contrib.gis.db import models
from django.db.models import Manager as GeoManager
from django.urls import reverse

from sequence.models import TransType, CameraMake, LabelType

UserModel = get_user_model()


class Challenge(models.Model):
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    transport_type = models.ForeignKey(TransType, on_delete=models.CASCADE, null=True, blank=True)
    camera_make = models.ManyToManyField(CameraMake)
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    geometry = models.TextField(default='')
    multipolygon = models.MultiPolygonField(null=True, blank=True)
    is_published = models.BooleanField(default=True)
    zoom = models.FloatField(default=5)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.now, blank=True)

    objects = GeoManager()

    def get_absolute_url(self):
        return reverse('challenge.challenge_detail', kwargs={'unique_id': str(self.unique_id)})

    def get_short_description(self):
        description = self.description
        if len(description) > 50:
            return description[0:80] + '...'
        else:
            return description

    def getTrasTypes(self):
        transport_type = self.transport_type
        t = []
        if transport_type is not None:
            t.append(transport_type.getFullName())

        return ', '.join(t)

    def get_transport_types_obj(self):
        transport_types = self.transport_type.all()
        return transport_types

    def get_camera_make(self):
        camera_makes = self.camera_make.all()
        t = []
        if camera_makes.count() > 0:
            for camera_make in camera_makes:
                t.append(camera_make.name)

        return ', '.join(t)


class LabelChallenge(models.Model):
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    label_type = models.ManyToManyField(LabelType)
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    geometry = models.TextField(default='')
    multipolygon = models.MultiPolygonField(null=True, blank=True)
    is_published = models.BooleanField(default=True)
    zoom = models.FloatField(default=5)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.now, blank=True)

    objects = GeoManager()

    def get_absolute_url(self):
        return reverse('label_challenge.challenge_detail', kwargs={'unique_id': str(self.unique_id)})

    def get_short_description(self):
        description = self.description
        if len(description) > 50:
            return description[0:80] + '...'
        else:
            return description

    def get_label_type_obj(self):
        label_types = self.label_type.all()
        return label_types

challenge/views.py
# Python packages
import json

from django.contrib import messages
from django.contrib.gis.geos import Point, Polygon, MultiPolygon, LineString
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, Sum
# Django Packages
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.http import Http404, JsonResponse

# Project packages
from accounts.models import CustomUser
# Custom Libs ##
from lib.functions import *
from sequence.models import Sequence, Image, ImageLabel
# That includes from .models import *
from .forms import *

# App packages

############################################################################

# def handler404(request, *args, **argv):
#     response = render(request, '404.html', {})
#     response.status_code = 404
#     return response

# def handler500(request, *args, **argv):
#     response = render(request, '500.html', {})
#     response.status_code = 500
#     return response

############################################################################

CAPTURE_CHALLENGE_DESCRIPTION = "Find or offer help on image collection projects to create fresh street-level imagery."
LABEL_CHALLENGE_DESCRIPTION = "Help label images to help people search for what's inside of it; from species of tree to road surface type."


############################################################################


def index(request):
    return redirect('challenge.challenge_list')


@my_login_required
def challenge_create(request):
    if request.method == "POST":
        form = ChallengeForm(request.POST)

        if form.is_valid():
            challenge = form.save(commit=False)
            challenge.user = request.user
            geometry = json.loads(challenge.geometry)

            multipolygon = MultiPolygon()
            for geo in geometry:
                coordinates = geo['geometry']['coordinates'][0]
                line_string = LineString()
                first_point = None
                for i in range(len(coordinates)):
                    coord = coordinates[i]
                    if i == 0:
                        first_point = Point(coord[0], coord[1])
                        continue
                    point = Point(coord[0], coord[1])
                    if i == 1:
                        line_string = LineString(first_point.coords, point.coords)
                    else:
                        line_string.append(point.coords)
                polygon = Polygon(line_string.coords)
                multipolygon.append(polygon)
            challenge.multipolygon = multipolygon

            for geo in geometry:
                geo['properties']['challenge_id'] = str(challenge.unique_id)
            challenge.geometry = json.dumps(geometry)

            challenge.save()
            camera_make = form.cleaned_data['camera_make']
            if camera_make is not None and len(camera_make) > 0:
                for cm in camera_make:
                    cam = CameraMake.objects.filter(name=cm).first()
                    if cam is not None:
                        challenge.camera_make.add(cam)

            transport_type = form.cleaned_data['transport_type']
            if transport_type is not None:
                challenge.transport_type = transport_type

            messages.success(request, 'A challenge was created successfully.')

            return redirect('challenge.my_challenge_list')
    else:
        form = ChallengeForm()
    content = {
        'form': form,
        'pageName': 'Create Challenge',
        'pageTitle': 'Create Challenge'
    }
    return render(request, 'challenge/capture/create.html', content)


@my_login_required
def challenge_edit(request, unique_id):
    challenge = get_object_or_404(Challenge, unique_id=unique_id)
    if request.method == "POST":
        form = ChallengeForm(request.POST, instance=challenge)
        if form.is_valid():
            challenge = form.save(commit=False)
            challenge.user = request.user
            challenge.updated_at = datetime.now()
            challenge.save()

            camera_make = form.cleaned_data['camera_make']
            geometry = json.loads(challenge.geometry)

            multipolygon = MultiPolygon()
            for geo in geometry:
                coordinates = geo['geometry']['coordinates'][0]
                line_string = LineString()
                first_point = None
                for i in range(len(coordinates)):
                    coord = coordinates[i]
                    if i == 0:
                        first_point = Point(coord[0], coord[1])
                        continue
                    point = Point(coord[0], coord[1])
                    if i == 1:
                        line_string = LineString(first_point.coords, point.coords)
                    else:
                        line_string.append(point.coords)
                polygon = Polygon(line_string.coords)
                multipolygon.append(polygon)
            challenge.multipolygon = multipolygon

            for geo in geometry:
                geo['properties']['challenge_id'] = str(challenge.unique_id)
            challenge.geometry = json.dumps(geometry)
            challenge.save()

            if camera_make is not None and len(camera_make) > 0:
                for cm in camera_make:
                    cam = CameraMake.objects.filter(name=cm).first()
                    if cam is not None:
                        challenge.camera_make.add(cam)

            transport_type = form.cleaned_data['transport_type']
            if transport_type is not None:
                challenge.transport_type = transport_type

            messages.success(request, 'Challenge "%s" is updated successfully.' % challenge.name)
            return redirect('challenge.index')
    else:
        form = ChallengeForm(instance=challenge)
    content = {
        'form': form,
        'pageName': 'Edit Challenge',
        'challenge': challenge,
        'pageTitle': challenge.name + ' - Edit Challenge'
    }
    return render(request, 'challenge/capture/edit.html', content)


@my_login_required
def my_challenge_delete(request, unique_id):
    challenge = get_object_or_404(Challenge, unique_id=unique_id)
    if challenge.user == request.user:
        challenge.camera_make.clear()
        challenge.transport_type.clear()
        challenge.delete()
        messages.success(request, 'Challenge "%s" is deleted successfully.' % challenge.name)
    else:
        messages.error(request, "This user hasn't permission")

    return redirect('challenge.index')


def challenge_list(request):
    challenges = None
    page = 1
    if request.method == "GET":
        form = ChallengeSearchForm(request.GET)
        page = request.GET.get('page')
        if page is None:
            page = 1
        if form.is_valid():
            challenges = Challenge.objects.all().filter(is_published=True)
            name = form.cleaned_data['name']
            transport_type = form.cleaned_data['transport_type']
            camera_makes = form.cleaned_data['camera_make']
            challenge_type = form.cleaned_data['challenge_type']

            if name is not None:
                challenges = challenges.filter(name__icontains=name)

            if transport_type is not None:
                children_trans_type = TransType.objects.filter(parent=transport_type)
                if children_trans_type.count() > 0:
                    types = [transport_type]
                    for t in children_trans_type:
                        types.append(t)
                    challenges = challenges.filter(transport_type__in=types)
                else:
                    challenges = challenges.filter(transport_type=transport_type)

            current_time = datetime.now()
            if challenge_type is not None and challenge_type == 'active':
                challenges = challenges.filter(end_time__gte=current_time)
            if challenge_type is not None and challenge_type == 'completed':
                challenges = challenges.filter(end_time__lt=current_time)
            if camera_makes is not None and len(camera_makes) > 0:
                challenges = challenges.filter(camera_make__name__in=camera_makes)

    if challenges is None:
        challenges = Challenge.objects.all().filter(is_published=True)
        form = ChallengeSearchForm()

    paginator = Paginator(challenges.order_by('-created_at'), 10)

    try:
        pChallenges = paginator.page(page)
    except PageNotAnInteger:
        pChallenges = paginator.page(1)
    except EmptyPage:
        pChallenges = paginator.page(paginator.num_pages)

    first_num = 1
    last_num = paginator.num_pages
    if paginator.num_pages > 7:
        if pChallenges.number < 4:
            first_num = 1
            last_num = 7
        elif pChallenges.number > paginator.num_pages - 3:
            first_num = paginator.num_pages - 6
            last_num = paginator.num_pages
        else:
            first_num = pChallenges.number - 3
            last_num = pChallenges.number + 3
    pChallenges.paginator.pages = range(first_num, last_num + 1)
    pChallenges.count = len(pChallenges)

    content = {
        'challenges': pChallenges,
        'form': form,
        'pageName': 'Challenges',
        'pageTitle': 'Challenges',
        'pageDescription': CAPTURE_CHALLENGE_DESCRIPTION,
        'page': page
    }

    return render(request, 'challenge/capture/list.html', content)


@my_login_required
def my_challenge_list(request):
    challenges = None
    page = 1
    if request.method == "GET":
        form = ChallengeSearchForm(request.GET)
        page = request.GET.get('page')
        if page is None:
            page = 1
        if form.is_valid():
            challenges = Challenge.objects.all().filter(user=request.user)

            name = form.cleaned_data['name']

templates/challenge/label/create.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block app_label_challenge %}active{% endblock %}
{% block app_style %}<link rel="stylesheet" href="{% static 'css/challenge_style.css' %}">{% endblock %}
{% block content %}
<div class="main-body">
    <div class="left-side d-flex flex-column justify-content-between">
        <div>
            <div class="p-4">
                <h4 class="text-center text-primary mt-3">Create Label Challenge</h4>

                <p>Draw the areas you are available for work:</p>

                <div class="mapbox-actions d-flex justify-content-between mb-3">
                    <div class="col-6 pl-0 pr-1">
                        <button class="btn btn-primary w-100" id="draw_polygon">Draw Polygon</button>
                    </div>

                    <div class="col-6 pr-0 pl-1">
                        <button class="btn btn-danger w-100" id="delete_polygon">Delete Polygon</button>
                    </div>
                </div>

                <form method="POST" class="post-form" id="challenge_create_form">
                    {% csrf_token %}
                    {% load bootstrap4 %}
                    {% bootstrap_css %}
                    {{ form.media }}
                    {{ form.as_p }}
                    <textarea class="d-none" name="new_label_types" id="new_label_types" ></textarea>
                    <div>
                        <span>You can add your own label type.</span>
                        <label>Your own label types: </label>
                        <div id="new_label_types_box">
                        </div>


                        <div class="d-flex justify-content-between mt-2 mb-2">
                            <button type="button" class="btn btn-sm btn-outline-primary" onclick="showModal()">Add a label type</button>
                            <button type="button" class="btn btn-sm btn-outline-danger d-none" id="deleteLabelTypeBtn" onclick="deleteLabelType()">Delete a label type</button>
                        </div>
                    </div>
                    <div class="form-group text-right">
                        <button type="button" class="save btn btn-primary save-btn">Save</button>
                    </div>
                </form>
            </div>
        </div>
        {% include 'components/copyrite.html' %}
    </div>
    <div class="right-board bg-light">
        <div id="map">

        </div>
    </div>
</div>

<div class="modal fade" id="newLabelTypeModal" tabindex="-1" role="dialog" aria-labelledby="newLabelTypeModalHeader" aria-hidden="true">
    <div class="modal-dialog ml-auto mr-auto" style="margin-top: 130px !important;" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newLabelTypeModalHeader">Add a label type</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div>
                    <div class="d-flex justify-content-between">
                        <div>
                            <input type="radio" id="exist_name" name="add_type" value="exist_name" checked>
                            <label for="exist_name">Use existing parent</label>
                        </div>

                        <div>
                            <input type="radio" id="full_name" name="add_type" value="full_name">
                            <label for="full_name">Use full type</label>
                        </div>
                    </div>
                    <form class="" id="add_new_label_form">
                        <p>
                            <label>Parent Label:</label>
                            <select class="form-control" id="parent_key">
                                <option value="">---</option>
                                {% for label_type in label_types %}
                                    <option value="{{ label_type }}">{{ label_type }}</option>
                                {% endfor %}
                            </select>
                        </p>

                        <p id="input_name_p">
                            <label for="new_label_type">Child Label:</label>
                            <input class="form-control" data-validation="alphanumeric required" data-validation-allowing=" " id="new_label_type" />
                        </p>
                    </form>

                    <form class="d-none" id="add_new_label_form_full_name">
                        <p id="input_full_name_parent_p">
                            <label for="new_full_label_parent_type">Parent Label:</label>
                            <input class="form-control" data-validation="alphanumeric" data-validation-optional="true" data-validation-allowing="-"  id="new_full_label_parent_type" />
                        </p>

                        <p id="input_full_name_p">
                            <label for="new_full_label_type">Child Label:</label>
                            <input class="form-control" data-validation="alphanumeric" data-validation-allowing="-" id="new_full_label_type" />

                        </p>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary mr-2" id="add_label_type_btn">Add</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
  <script>
      var add_type = 'exist_name';
      var own_types = [];
    var showModal = function() {
        $('#newLabelTypeModal').modal('show');
    }

    $('input[name="add_type"]').change(function () {
        add_type = $(this).val();
        if($(this).val() == 'full_name')
        {
            $('#add_new_label_form_full_name').removeClass('d-none');
            $('#add_new_label_form').addClass('d-none');
        }
        else {
            $('#add_new_label_form_full_name').addClass('d-none');
            $('#add_new_label_form').removeClass('d-none');
        }
    });
    var current_selected_tag = ''
    var clickLabelTag = function(key) {
        var $spanObj = $('span.tag[data-key=' + key + ']');
        if ($spanObj.text() == key && $('span.tag.selected').hasClass('selected')) {
            $('span.tag.selected').removeClass('selected');
            $('#deleteLabelTypeBtn').addClass('d-none');
            return;
        }
        $('span.tag.selected').removeClass('selected')
        $spanObj.addClass('selected');
        $('#deleteLabelTypeBtn').removeClass('d-none')
    }

    var deleteLabelType = function() {
        var key = $('span.tag.selected').text();
        if (own_types.indexOf(key) > -1) {
            own_types.splice(own_types.indexOf(key), 1);
        }
        $('span.tag.selected').remove();
        $('#deleteLabelTypeBtn').addClass('d-none');
    }

    $('#add_label_type_btn').click(function () {
        var label = '';
        var parent_label = '';
        if (add_type == 'exist_name' && $('#add_new_label_form').isValid()) {
            parent_label = $('#parent_key').val();
            var new_label_type = $('#new_label_type').val();
            var str_ary = new_label_type.split(' ');


            console.log(str_ary.length);
            if (str_ary.length > 0) {
                for (var i=0; i<str_ary.length; i++) {
                    if (str_ary[i] != '') {
                        if (label == '')
                            label = str_ary[i]
                        else
                            label += '-' + str_ary[i]
                    }
                }

                if (new_label_type.length > 0 && label == '') {
                    $('#add_new_label_form #input_name_p').addClass('has-error');
                    $('#add_new_label_form #input_name_p').removeClass('has-success');
                    $('#new_label_type').addClass('error');
                    $('#add_new_label_form #input_name_p').append('<span class="help-block form-error">At least one character must be alphabetnumic.</span>')
                    return;
                }
            }
            else
                label = new_label_type;
        }
        if (add_type == 'full_name' && $('#add_new_label_form_full_name').isValid())
        {
            label = $('#new_full_label_type').val();
            parent_label = $('#new_full_label_parent_type').val();
            if (label.search('--') >= 0) {
                $('#input_full_name_p').addClass('has-error');
                $('#input_full_name_p').removeClass('has-success');
                $('#new_full_label_type').addClass('error');
                $('#input_full_name_p').append('<span class="help-block form-error">The input value can\'t contain "--".</span>')
                return;
            }

            if (parent_label.search('--') >= 0) {
                $('#input_full_name_parent_p').addClass('has-error');
                $('#input_full_name_parent_p').removeClass('has-success');
                $('#new_full_label_parent_type').addClass('error');
                $('#input_full_name_parent_p').append('<span class="help-block form-error">The input value can\'t contain "--".</span>')
                return;
            }
        }
        if (label == '') return;

        if (own_types.indexOf(label) > -1) {
            toastr.info('The value already exist in your own label type list.')
            return;
        }
        if (parent_label != '')
            label = parent_label + '--' + label
        own_types.push(label);
        var html_label_type = '<span class="tag d-inline-block" style="font-size: 16px; cursor: pointer" onclick="clickLabelTag(\'' + label + '\')" data-key="' + label + '">' + label + '</span>';
        $('#new_label_types_box').append(html_label_type);
        $('#newLabelTypeModal').modal('hide');
    });
    // TO MAKE THE MAP APPEAR YOU MUST
	// ADD YOUR ACCESS TOKEN FROM
	// https://account.mapbox.com
	mapboxgl.accessToken = mapboxToken;
    var map = new mapboxgl.Map({
        container: 'map', // container id
        style: 'mapbox://styles/mapbox/streets-v11', //hosted style id
        center: [-74.5, 40], // starting position
        zoom: 3 // starting zoom
    });

    map.addControl(
        new MapboxGeocoder({
            accessToken: mapboxgl.accessToken,
            localGeocoder: coordinatesGeocoder,
            zoom: 1,
            placeholder: '',
            mapboxgl: mapboxgl
        }), 'top-left'
    );

    var draw = new MapboxDraw({
        displayControlsDefault: false,
        controls: {
            polygon: true,
            trash: true
        }
    });
    map.addControl(draw);

    map.on('draw.create', updateArea);
    map.on('draw.delete', updateArea);
    map.on('draw.update', updateArea);

    function updateArea(e) {
        var data = draw.getAll();
        var zoom = map.getZoom();
        console.log(zoom);
        console.log(data);
        var geometryData = [];
        data.features.forEach(function (item, index) {
            geometryData.push(item);
        });
        var geometryDataStr = JSON.stringify(geometryData);
        console.log(geometryData)
        $('#id_geometry').val(geometryDataStr);
        $('#id_zoom').val(zoom);
    }

    $('.save-btn').click(function() {
        if ($('#id_geometry').val() == '' || $('#id_geometry').val() == '[]')
        {
            Swal.fire({
                title: 'Required One or More Area.',
                icon: 'error',
                showCloseButton: true,
            })
            return false;
        }
        if (own_types.length > 0) {
            var own_types_str = own_types.join(',');
            $('#new_label_types').val(own_types_str)
        }
        $('#challenge_create_form').submit()
        return true;
    })

    $('#draw_polygon').click(function() {
        $('.mapbox-gl-draw_polygon').trigger('click');
    })

    $('#delete_polygon').click(function() {
        $('.mapbox-gl-draw_trash').trigger('click');
    })
  </script>
{% endblock %}